{{- define "mychart.labels" }}
  labels:
    custom: lennert
    generator: helm
    date: {{ now | htmlDate }}
{{- end }}
{{- with .Values.tlsSecrets }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}
   {{- template "mychart.labels" }}

data:
  {{- range $key, $val := $.Values.favorite }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}

  {{- range $key, $val := $.Release }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}

{{- end }}