
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-configmap
  labels: 
{{ include "mychart.app" . | indent 4}}

data:
  {{- range $key, $val := $.Values.favorite }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}

  {{- range $key, $val := $.Release }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}